#!/bin/bash
#Simple bash script that will check to see if a screen session
#with irssi is already running, otherwise it will start one for you

ON=`screen -ls | grep chat | wc -l`
if [ $ON == 0 ]; then
  screen -S chat irssi
else
  screen -x chat
fi
